import {
  BIRTHDAY, LOVE, DECORATION,
} from './consts';

function importAll(r) {
  const images = [];
  r.keys().forEach((item) => {
    images[item.replace('./', '')] = r(item);
  });
  return images;
}

const images = importAll(require.context('../images', false, /\d.(png|jpe?g)$/));

const dataArr = [
  {
    id: '5',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['yellow'],
    price: 22.00,
    occasions: [BIRTHDAY, DECORATION],
    url: images['5.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '6',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 12.95,
    occasions: [],
    url: images['6.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '7',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 30.00,
    occasions: [],
    url: images['7.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '9',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 10.95,
    occasions: [DECORATION],
    url: images['9.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '10',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 20.95,
    occasions: [DECORATION, BIRTHDAY],
    url: images['10.jpg'],
    collection: 'colorful',
    trending: true,
    recommended: true,
  },
  {
    id: '13',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange'],
    price: 30.00,
    occasions: [DECORATION],
    url: images['13.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '17',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 40.00,
    occasions: [LOVE, BIRTHDAY],
    url: images['17.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '18',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange'],
    price: 20.95,
    occasions: [DECORATION, BIRTHDAY],
    url: images['18.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '19',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 50.95,
    occasions: [LOVE],
    url: images['19.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '20',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 30.00,
    occasions: [DECORATION, LOVE],
    url: images['20.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '21',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange', 'white'],
    price: 12.95,
    occasions: [DECORATION, BIRTHDAY],
    url: images['21.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '22',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange', 'yellow'],
    price: 65.00,
    occasions: [BIRTHDAY, LOVE, DECORATION],
    url: images['22.jpg'],
    collection: 'colorful',
    trending: true,
    recommended: true,
  },
  {
    id: '23',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange', 'pink'],
    price: 55.00,
    occasions: [BIRTHDAY, LOVE, DECORATION],
    url: images['23.jpg'],
    collection: 'colorful',
    trending: true,
    recommended: false,
  },
  {
    id: '27',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white', 'yellow'],
    price: 38.00,
    occasions: [DECORATION],
    url: images['27.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: true,
  },
  {
    id: '30',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 20.00,
    occasions: [DECORATION],
    url: images['30.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '31',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['red', 'white'],
    price: 12.50,
    occasions: [DECORATION, LOVE],
    url: images['31.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '40',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange', 'yellow'],
    price: 25.95,
    occasions: [LOVE, DECORATION, BIRTHDAY],
    url: images['40.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '42',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 45.00,
    occasions: [LOVE],
    url: images['42.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '43',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 45.95,
    occasions: [LOVE],
    url: images['43.jpg'],
    collection: 'colorful',
    trending: true,
    recommended: false,
  },
  {
    id: '44',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white', 'yellow'],
    price: 60.00,
    occasions: [DECORATION, LOVE],
    url: images['44.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '47',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 35.95,
    occasions: [DECORATION, BIRTHDAY],
    url: images['47.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '48',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'yellow', 'red'],
    price: 50.95,
    occasions: [BIRTHDAY, LOVE],
    url: images['48.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '49',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 30.00,
    occasions: [DECORATION],
    url: images['49.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '50',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['red', 'yellow'],
    price: 35.95,
    occasions: [DECORATION, LOVE],
    url: images['50.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '51',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 25.95,
    occasions: [DECORATION, LOVE],
    url: images['51.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '52',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['red', 'yellow'],
    price: 32.00,
    occasions: [DECORATION, BIRTHDAY],
    url: images['52.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '53',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'red', 'yellow'],
    price: 25.00,
    occasions: [DECORATION, LOVE],
    url: images['53.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '54',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 22.00,
    occasions: [LOVE, DECORATION],
    url: images['54.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '55',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 40.95,
    occasions: [LOVE],
    url: images['55.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '56',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['yellow', 'red'],
    price: 45.00,
    occasions: [DECORATION, LOVE],
    url: images['56.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '57',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['red'],
    price: 35.95,
    occasions: [DECORATION, LOVE],
    url: images['57.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '58',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 18.95,
    occasions: [DECORATION, LOVE],
    url: images['58.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '61',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['yellow', 'orange'],
    price: 22.00,
    occasions: [DECORATION, BIRTHDAY],
    url: images['61.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },

  {
    id: '63',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 35.00,
    occasions: [DECORATION, LOVE],
    url: images['63.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '64',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 35.95,
    occasions: [DECORATION, LOVE],
    url: images['64.jpg'],
    collection: 'light',
    trending: true,
    recommended: false,
  },
  {
    id: '65',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange'],
    price: 35.95,
    occasions: [DECORATION],
    url: images['65.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '66',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 10.95,
    occasions: [DECORATION, LOVE],
    url: images['66.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '67',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 55.00,
    occasions: [LOVE],
    url: images['67.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '68',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 45.95,
    occasions: [LOVE],
    url: images['68.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '69',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 40.00,
    occasions: [LOVE],
    url: images['69.jpg'],
    collection: 'light',
    trending: true,
    recommended: false,
  },
  {
    id: '73',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'orange'],
    price: 45.95,
    occasions: [DECORATION],
    url: images['73.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '76',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 20.95,
    occasions: [DECORATION, LOVE],
    url: images['76.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '77',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 20.95,
    occasions: [DECORATION, LOVE],
    url: images['77.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '78',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 40.00,
    occasions: [LOVE],
    url: images['78.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '80',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 45.00,
    occasions: [LOVE],
    url: images['80.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '82',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['orange'],
    price: 30.00,
    occasions: [DECORATION, BIRTHDAY, LOVE],
    url: images['82.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '83',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['red'],
    price: 55.00,
    occasions: [LOVE],
    url: images['83.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '85',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 40.95,
    occasions: [DECORATION],
    url: images['85.jpg'],
    collection: 'light',
    trending: false,
    recommended: false,
  },
  {
    id: '86',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 25.00,
    occasions: [DECORATION],
    url: images['86.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '87',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white'],
    price: 55.00,
    occasions: [DECORATION, BIRTHDAY, LOVE],
    url: images['87.jpg'],
    collection: 'light',
    trending: true,
    recommended: false,
  },
  {
    id: '88',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['white', 'pink'],
    price: 40.00,
    occasions: [DECORATION, LOVE],
    url: images['88.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '91',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 35.00,
    occasions: [DECORATION, BIRTHDAY, LOVE],
    url: images['91.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '92',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink', 'white'],
    price: 55.00,
    occasions: [LOVE],
    url: images['92.jpg'],
    collection: 'light',
    trending: true,
    recommended: false,
  },
  {
    id: '93',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['yellow'],
    price: 20.95,
    occasions: [DECORATION],
    url: images['93.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '94',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['yellow', 'orange'],
    price: 35.95,
    occasions: [DECORATION, BIRTHDAY],
    url: images['94.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '95',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['red', 'pink'],
    price: 55.00,
    occasions: [LOVE],
    url: images['95.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '96',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 55.00,
    occasions: [LOVE],
    url: images['96.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
  {
    id: '97',
    title: 'Lorem ipsum dolor sit amet.',
    longDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    shortDescription: 'Loren ipsum dolor sit amet, consectetur adipiscing elit.',
    colors: ['pink'],
    price: 20.00,
    occasions: [LOVE],
    url: images['97.jpg'],
    collection: 'colorful',
    trending: false,
    recommended: false,
  },
];

export default dataArr;
