export const ADD_TO_BAG = 'ADD_TO_BAG';
export const DELETE_FROM_BAG = 'DELETE_FROM_BAG';
export const INCREASE_BILLING = 'INCREASE_BILLING';
export const DECREASE_BILLING = 'DECREASE_BILLING';
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
